language: python
python:
  - "2.7"
before_script:
  - psql -c 'create database dashboard;' -U postgres
install:
  - easy_install -U setuptools
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg
script: bin/py.test
